name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      messages: ${{ steps.result.outputs.messages.Body }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Custom Actions test
        id: result
        uses: ./
        with:
          QUEUE_NAME: ${{ secrets.QUEUE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      

  consume: 
    runs-on: ubuntu-latest
    needs: test 
    steps:   
      - name: Display Result 
        run: echo "${{ needs.test.outputs.messages }}"         
