name: Tests 

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Custom Actions test 
        uses: ./
        with:
          queue-name: 'seccl-sqs-vpc-8e557739'